#!/usr/bin/python
# vim: set fileencoding=utf8 :
#
# :: Invasion Tux
# :: Ultima modificacion : lunes, 20 de abril de 2009
# :: Script realizado por makiolo (makiolo@gmail.com)  (Licencia ver LICENCIA.txt)
# :: Ultima version : http://blogricardo.wordpress.com/2009/04/07/wiithon-wbfs-gui-para-wii/
# :: Dependencias : sudo apt-get install nautilus-actions imagemagick wget rar
#

import sys , os , subprocess , time , glob , fnmatch
import pygtk
pygtk.require('2.0')
import gtk
from gtk import glade

# Constantes
RUTA = os.path.dirname(sys.argv[0]) # deben estar junto al script las dependencias
WBFS_APP = RUTA+"/"+"wbfs"
DETECTOR_WBFS = RUTA+"/"+"wiithon_autodetectar"
DETECTOR_WBFS_LECTOR = RUTA+"/"+"wiithon_autodetectar_lector"
HOME = os.path.expanduser("~")
ACUERDO = HOME+"/.wiithon_acuerdo"

# Variables auxiliares ,  no modificar
DEVICE = ""
ISO = ""
COMANDO = ""
ID_JUEGO = ""
PAUSA = False
FABRICANTE = ""
listaFicheros = []
correctos = []
erroneos = []
SALIDA_FORZADA = False
BLACK_LIST = "/\"\'$&|[]"
PARAMETROS = []
GUI = False

def instalarJuego(DEVICE):
	global DETECTOR_WBFS
	salida = ""
	print "Buscando un Disco de Wii ..."
	subProceso = getPopen(DETECTOR_WBFS_LECTOR)
	#Espera que acabe
	subProceso.wait()
	for linea in subProceso.stdout:
		salida = salida + linea
		
	# Le quito el ultimo salto de linea y forma la lista cortando por saltos de linea
	listaParticiones = []
	if (salida <> ""):
		listaParticiones = salida[:-1].split("\n")
	
	numListaParticiones = len(listaParticiones)
	if(numListaParticiones<=0):
		print "No se ha encontrado ningún disco de la Wii"
	elif(numListaParticiones > 1):
		print "Hay más de un juego de la Wii, deja solo 1 para eliminar la ambigüedad"
	else:# 1 juego de wii
		try:
			cachos = listaParticiones[0].split(":")
			LECTOR_DVD = cachos[0]
			FABRICANTE_DVD = cachos[1]
			MAGIC_DVD = getMagicISO(LECTOR_DVD)
			SALIDA = os.getcwd()+"/"+MAGIC_DVD+".iso"
			reemplazada = False
			if (comprobarExistencia(SALIDA)):
				print "Ya hay una ISO en : " + SALIDA
				respuesta = raw_input("Desea reemplazarla (S/N) : ")
				if(respuesta.lower() == "s" or respuesta.lower() == "si"):
					reemplazada = False
				else:
					reemplazada = True
			print FABRICANTE_DVD + " a un ISO temporal de 4.4GB en = " + MAGIC_DVD+".iso ..."
			if( reemplazada or (os.system("dd if="+LECTOR_DVD+" of="+SALIDA+" bs=1M")==0) ):
				if ( anadirISO(DEVICE , SALIDA)):
					if( descargarCaratula(MAGIC_DVD) ):
						print "Caratula descargada como "+os.getcwd()+"/"+MAGIC_DVD+".png"
					else:
						print "No se ha encontrado caratula para el juego " + MAGIC_DVD
				else:
					print "Error al pasar la ISO al disco duro"
				print "wiithon no borra la ISO temporal, puedes borrarla si no la necesitas"
			else:
				print "Error al dumpear la ISO"
		except KeyboardInterrupt:
			print "Interrumpido por el usuario"

def comprobarExistencia(fichero):
	return os.path.exists(fichero)

def tieneCaracteresRaros(cadena):
	global BLACK_LIST
	# Lista negra de caracteres que hacen que deje de ser un expresion regular
	for i in range(len(cadena)):
		for j in range(len(BLACK_LIST)):
			if (cadena[i]==BLACK_LIST[j]):
				return True
	return False

def eliminarComillas(string):
	'''
	Primera letra				[:1]
	Ultima letra				[-1:]
	Todo excepto primera letra	[1:]
	Todo excepto ultima letra	[:-1]
	'''
	if( string[:1]=="'" or string[:1]=="\"" ):
		if( string[-1:]=="'" or string[-1:]=="\"" ):
			string = string[1:]
			string = string[:-1]
	return string

def getExtension(fichero):
	fichero = eliminarComillas(fichero)
	posPunto = fichero.rfind(".")
	return fichero[posPunto+1:len(fichero)].lower()

def getNombreFichero(fichero):
	fichero = eliminarComillas(fichero)
	posPunto = fichero.rfind(".")
	return fichero[0:posPunto]

def getMagicISO(imagenISO):
	f = open(imagenISO , "r")
	magic = f.read(6)
	f.close()
	return magic

def ordenarPorNombre(juego1 , juego2):
	return cmp( juego1[1].lower() , juego2[1].lower() )

def getListaJuegos(DEVICE):
	global WBFS_APP
	subProceso = getPopen("sudo "+WBFS_APP+" -p "+DEVICE+" ls")
	#Espera que acabe
	subProceso.wait()
	salida = []
	for linea in subProceso.stdout:
		cachos = linea.split(";")
		if(len(cachos)==3):
			#Elimina el salto de linea del ultimo cacho
			cachos[2] = cachos[2][:-1].split("\n")[0]
			#Añade el juego a la lista
			salida.append( [ cachos[0] , cachos[1] , cachos[2] ] )
	salida.sort(ordenarPorNombre)
	return salida

def verificarTodosLosJuegos(DEVICE):
	listaJuegos = getListaJuegos(DEVICE)
	listaCorruptos = []
	numJuegos = len(listaJuegos)
	if(numJuegos > 0):
		print "--------------------------------------------------------------------------------"
		print "%6s\t%-40s\t%s" % ("IDGAME","TITULO" , "¿Corrupto?")
		print "--------------------------------------------------------------------------------"
		for juego in listaJuegos:
			salida = os.system("sudo "+WBFS_APP+" -p "+DEVICE+" check "+juego[0])
			if( salida == 0 ):
				corrupto = "NO ESTA CORRUPTO"
			else:
				corrupto = "¡¡ ESTA CORRUPTO !!"
				listaCorruptos.append(juego)
			print "%s\t%-40s\t%s" % ( juego[0] , juego[1] , corrupto)
	numCorruptos = len(listaCorruptos)
	if (numCorruptos > 0):
		print "--------------------------------------------------------------------------------"
		print "Lista de juegos corruptos"
		print "--------------------------------------------------------------------------------"
		for juego in listaCorruptos:
			print "%s\t%-40s" % ( juego[0] , juego[1])
		print "--------------------------------------------------------------------------------"
		print "Hay *"+str(numCorruptos)+"* juegos corruptos se recomienda que los desinstale"
		print "--------------------------------------------------------------------------------"
		respuesta = raw_input("¿Quieres desinstalarlos? (S/N) ")
		if(respuesta.lower() == "s" or respuesta.lower() == "si"):
			for juego in listaCorruptos:
				if (borrarJuego(DEVICE , juego[0])):
					print juego[0] + " borrado correctamente"
				else:
					print "ERROR : " + juego[0] + " NO se ha borrado correctamente"
		else:
			print "Saliendo. No se ha desinstalado nada"

def get_IDJUEGO_de_Lista(DEVICE):
	listaIDGAME = getListaJuegos(DEVICE)
	numJuegos = len(listaIDGAME)
	if(numJuegos > 0):
		print "--------------------------------------------------------------------------------"
		print "%3s\t%6s\t%-40s\t%7s\t%6s" % ("NUM","IDGAME","TITULO","TAMAÑO" , "¿Car.?")
		print "--------------------------------------------------------------------------------"
		i = 1
		for juego in listaIDGAME:
			ocupado = float(juego[2])
			if (existeCaratula(juego[0])):
				caratula = "SI"
			else:
				caratula = "NO"
			print "%3s\t%s\t%-40s\t%.2f GB\t%6s" % ( i , juego[0] , juego[1] , ocupado , caratula)
			i = i + 1
		print "--------------------------------------------------------------------------------"

		try:
			numJuego = int( raw_input("¿Indique el NUM del juego? : ") )
			# 1 <= numJuego <= numJuegos
			if ((1 <= numJuego) and (numJuego <= numJuegos)):
				try:
					return listaIDGAME[numJuego-1][0]
				except IndexError:
					print "Numero fuera de rango"
		except ValueError:
			print "El numero dado es incorrecto"
	return "DESCONOCIDO"

def listarISOs(DEVICE):
	listaIDGAME = getListaJuegos(DEVICE)
	numJuegos = len(listaIDGAME)
	if(numJuegos > 0):
		print "--------------------------------------------------------------------------------"
		print "%6s\t%-55s\t%7s\t%6s" % ("IDGAME","TITULO","TAMAÑO" , "¿Car.?")
		print "--------------------------------------------------------------------------------"
		for juego in listaIDGAME:
			ocupado = float(juego[2])
			if (existeCaratula(juego[0])):
				caratula = "SI"
			else:
				caratula = "NO"
			print "%s\t%-55s\t%.2f GB\t%6s" % ( juego[0] , juego[1] , ocupado , caratula)
		print "--------------------------------------------------------------------------------"
		print "\t\t\t\t\t\t\t%d juegos de WII" % numJuegos
	return numJuegos

def mostrarEspacioLibre(DEVICE):
	global WBFS_APP
	subProceso = getPopen("sudo "+WBFS_APP+" -p "+DEVICE+" df")
	subProceso.wait()
	salida = ""
	for linea in subProceso.stdout:
		salida = salida + linea
	cachos = salida.split(";")
	if(len(cachos) == 3):
		print "\t\t\t\t\t\t\tUsado : %.2f GB" % float(cachos[0])
		print "\t\t\t\t\t\t\tLibre : %.2f GB" % float(cachos[1])
		print "\t\t\t\t\t\t\tTotal : %.2f GB" % float(cachos[2])
		return True
	else:
		return False

def anadirISO(DEVICE , ISO):
	global WBFS_APP
	'''
	try:
		salida = os.system("sudo "+WBFS_APP+" -p "+DEVICE+" add \""+ISO+"\"")
		return salida == 0
	except KeyboardInterrupt:
		return False
	'''
	
	'''
	salida = ""
	subProceso = getPopen("sudo "+WBFS_APP+" -p "+DEVICE+" add \""+ISO+"\"")

	#Espera que acabe
	subProceso.wait()

	for linea in subProceso.stdout:
		salida = salida + linea
		print "----> " + salida
	'''	
	
	comando = "sudo "+WBFS_APP+" -p "+DEVICE+" add \""+ISO+"\""
	#comando = 'zenity --text "¿Cual es tu nombre?" --entry'
	entrada, salida = os.popen2(comando)
	linea = ""
	while True:
		letra = salida.read(1)
		if(letra == '\n'):
			linea = linea.strip()
			try:
				cachos = linea.split(";")
				porcentaje = float(cachos[0])
				hora = int(cachos[1])
				minutos = int(cachos[2])
				segundos = int(cachos[3])
				print "LLeva un %.2f%% quedan %d horas, %d minutos, %d segundos" % ( porcentaje , hora , minutos , segundos )
			except TypeError:
				pass
			linea = ""
		linea = linea + letra
	entrada.close()
	salida.close()
	return True


def renombrarISO(DEVICE , IDGAME , NUEVO_NOMBRE):
	global WBFS_APP
	try:
		salida = os.system("sudo "+WBFS_APP+" -p "+DEVICE+" rename "+IDGAME+" \""+NUEVO_NOMBRE+"\"")
		return salida == 0
	except KeyboardInterrupt:
		return False

def borrarJuego(DEVICE , ID_JUEGO):
	global WBFS_APP
	try:
		salida = os.system("sudo "+WBFS_APP+" -p "+DEVICE+" rm "+ID_JUEGO)
		return salida == 0
	except KeyboardInterrupt:
		return False
	except TypeError:
		return False

def extraerJuego(DEVICE , ID_JUEGO):
	global WBFS_APP
	try:
		salida = os.system("sudo "+WBFS_APP+" -p "+DEVICE+" extract "+ID_JUEGO)
		return salida == 0
	except KeyboardInterrupt:
		return False

	
def getPopen(comando):
	sp = subprocess
	return sp.Popen(comando.split() , stdout=sp.PIPE ,stderr=sp.STDOUT , close_fds=False , shell=False, universal_newlines= True)

def glob_get_dirs(path):
	''' 
	Devuelve una lista de directorios del directorio "path" 
	http://newspiritcompany.infogami.com/recursive_glob_py
	'''
	d = []
	try:
		for i in os.listdir(path):          
			if os.path.isdir(path+i):
				d.append(os.path.basename(i))

	except NameError, ne:
		print "NameError thrown=", ne
	except:
		pass
	return d

def rec_glob(path, mask):
	l = []
	if (sys.platform[:5] == "linux"):
		if path[-1] != '/':
			path = path + '/'
	else: # Realmente no lo he probado en windows
		if path[-1] != '\\':
			path = path + '\\'

	for i in glob_get_dirs(path):
		res = rec_glob(path + i, mask)
		l = l + res

	try:
		for i in os.listdir(path):
				
			ii = i
			i = path + i
			if os.path.isfile(i):
					# Lo parcheo para que no diferencie mayuculas
					#if fnmatch.fnmatch(ii, mask):
					if fnmatch.fnmatch(ii.lower() , mask):
							l.append(i)
	except NameError, ne:
		print "NameError=", ne
	except:
		pass
	return l
	
def informarAcuerdo():
	global SALIDA_FORZADA
	print "No me hago responsable de la aplicacion ni de la perdida de datos. No obstante, la particion NO va ha ser formateada, esta aplicacion añade , borra y lista juegos explicitamente mediante la ayuda de " + os.path.basename(WBFS_APP) + ". Esta información no volverá a aparecer si acepta el acuerdo."
	haElegido = False
	while( not haElegido ):
		respuesta = raw_input("Esta de acuerdo (S/N)? ")
		if  ( respuesta.lower() == "n" or respuesta.lower() == "no" ):
			print "No puedes usar esta aplicacion si no estas deacuerdo"
			SALIDA_FORZADA = True
		elif( respuesta.lower() == "s" or respuesta.lower() == "si" ):
			fAcuerdo = open(ACUERDO , "w")
			fAcuerdo.write("Acuerdo aceptado en la fecha " + time.asctime() + "\n")
			fAcuerdo.close()
			haElegido = True
		else:
			print "Opcion incorrecta"

def existeCaratula(IDGAME):
	return (comprobarExistencia(IDGAME+".png"))

def descargarCaratula(IDGAME, panoramica = False):
	if (existeCaratula(IDGAME)):
		return True
	else:
		origen = 'http://www.theotherzone.com/wii/'
		regiones = ['pal' , 'ntsc' , 'ntscj']
		if(panoramica):
			origen = origen + "widescreen/"
		descargada = False
		i = 0
		while ( not descargada and i<len(regiones)  ):
			origenGen = origen + regiones[i] + "/" + IDGAME + ".png"
			salida = os.system("wget --no-cache " + origenGen)
			descargada = (salida == 0)
			os.system("mogrify -resize 160x225 "+IDGAME+".png")
			i = i + 1
		return descargada

def descargarTodasLasCaratula(DEVICE , panoramica):
	listaIDGAME = getListaJuegos(DEVICE)
	ok = True
	for juego in listaIDGAME:
		if ( not descargarCaratula(juego[0] , panoramica) ):
			ok = False
	return ok

def buscarParticionWBFS():
	global DETECTOR_WBFS , SALIDA_FORZADA , FABRICANTE
	DEVICE = ""
	salida = ""
	subProceso = getPopen(DETECTOR_WBFS)
	#Espera que acabe
	subProceso.wait()
	for linea in subProceso.stdout:
		salida = salida + linea

	# Le quito el ultimo salto de linea y forma la lista cortando por saltos de linea
	listaParticiones = []
	if (salida <> ""):
		listaParticiones = salida[:-1].split("\n")

	# Borramos los elementos que no contengan /dev/
	# los que tengan /dev/ se corta por : y se coge el primer cacho
	i = 0	
	while ( i  < len(listaParticiones) ):
		if(listaParticiones[i].find("/dev/") == -1):
			del listaParticiones[i]
		else: # es una particion WBFS
			i = i + 1

	if(len(listaParticiones) <= 0):
		print "No se ha encontrado ningun dispositivo con particion WBFS."
		SALIDA_FORZADA = True
	elif(len(listaParticiones) > 1):
		print "Lista de particiones autodetectadas : "
		haElegido = False
		while( not haElegido ):
			i = 1
			for dispositivo in listaParticiones:
				print str(i) + " - Particion : " + dispositivo
				i = i + 1
			iSalir = str(i)
			print iSalir + " - Salir"	
			iElegido = raw_input("Elige la particion WBFS con la que va ha trabajar : ")
			if( iElegido == iSalir ):
				SALIDA_FORZADA = True
				haElegido = True
			else:
				try:
					DEVICE = listaParticiones[ int(iElegido) - 1 ]
					try:
						cachos = DEVICE.split(":")
						DEVICE = cachos[0]
						FABRICANTE = cachos[1]
					except:
						print "Error obteniendo el Fabricando del HD"
						SALIDA_FORZADA = True
					haElegido = True
				except IndexError:
					print "Fuera de rango"
				except ValueError:
					print "Valor incorrecto"
	else: # len(listaParticiones) == 1)
		DEVICE = listaParticiones[0]
		try:
			cachos = DEVICE.split(":")
			DEVICE = cachos[0]
			FABRICANTE = cachos[1]
		except:
			print "Error obteniendo el Fabricando del HD"
			SALIDA_FORZADA = True

	return DEVICE

def getListaUnica(lista):
	u = []
	for x in lista:
		if x not in u:
			u.append(x)
	return u

def getNombreISOenRAR(nombreRAR):
	comando = "rar lt -c- '"+nombreRAR+"' | grep -i '.iso' | awk -F'.iso'  '{print $1}' | awk -F' ' '{print $0\".iso\"}' | sed 's/^ *//' | sed 's/ *$//'"
	tuberia = os.popen(comando)
	salida_estandar = tuberia.readlines()
	tuberia.close()
	for linea in salida_estandar:
		# Quitar el salto de linea
		linea = linea[:-1]
		if( getExtension(linea)=="iso" ):
			return linea
	return ""

def descomprimirRARconISODentro( nombreRAR , nombreISO ):
	try:
		salida = os.system("rar e -o- \""+nombreRAR+"\" \""+nombreISO+"\"")
		return (salida == 0)
	except KeyboardInterrupt:
		return False

# En desarrollo
# Se pasa como parametro ej: /dev/sdb2
def redimensionarParticionWBFS(particion):
	# 57 42 46 53 00 0b 85 30
	# 57 42 46 53 00 29 ea eb

	comando = "sudo fdisk -lu | grep -v 'MB' | grep '"+particion+"' | awk '{print $3-$2+1}'"
	entrada, salida = os.popen2(comando)
	salida = salida.read()

	offset = 0x4
	valor = int(salida)

	print "Se va escribir en la particion %s : %x:%x" % ( particion , offset , valor )
	respuesta = raw_input("¿Seguir? (S/N)\n")

	if (respuesta.lower() == 's'):
		byte1 = (valor & 0xFF000000) >> 8*3
		byte2 = (valor & 0x00FF0000) >> 8*2
		byte3 = (valor & 0x0000FF00) >> 8
		byte4 = (valor & 0x000000FF)

		f = open(particion , "wb")
		f.seek(offset , os.SEEK_SET)
		f.write('%c%c%c%c' % ( byte1 , byte2 , byte3 , byte4 ) )
		f.close()
		print "4 bytes escritos."
	else:
		print "sin cambios."

############# GUI GTK #########################

def cb(treeview, path, view_column):
    global xml
    xml.get_widget('caratula').set_from_file('glade/images/rock2.jpg')

############## MAIN ###########################

# Leemos parametros
for parametro in sys.argv:
	if ( parametro == sys.argv[0] ):
		pass
	elif( parametro == "-p" ):
		PAUSA = True
	elif( parametro.find("=") != -1 ):
		cacho_izq = parametro[:parametro.find("=")]
		cacho_der = parametro[parametro.find("=")+1:]
		if( cacho_izq=="--trabajo" or cacho_izq=="--work" ):
			if(os.path.isfile(cacho_der)):
				cacho_der = os.path.dirname(cacho_der)
			try:
				os.chdir(cacho_der)
			except:
				pass
	else:
		PARAMETROS.append(parametro)

PARAMETROS = getListaUnica(PARAMETROS)
numParametros = len(PARAMETROS)

GUI = numParametros == 0

if(not GUI):
	#Se puede forzar la salida por no aceptar el acuerdo
	if( not comprobarExistencia(ACUERDO)):
		informarAcuerdo()

	#Se puede forzar la salida por no encontrar particion
	DEVICE = buscarParticionWBFS()

	#Comprobamos si tiene algun juego
	listaJuegos = getListaJuegos(DEVICE)
	hayJuegos = len(listaJuegos) > 0
else:
	SALIDA_FORZADA = True

	print " ***********************************"
	print " ******** GUI EN DESARROLLO ********"
	print " ***********************************"
	xml = gtk.glade.XML('glade/me_gusta_tipo_rythimbox.glade')

	ls = gtk.ListStore(str,str,str,str,str)

	ls.append(('Rock Band 2','asdas','asdas','asdas','asdas',))
	ls.append(('Animal Crossing','asdas','asdas','asdas','asdas', ))
	ls.append(('Resident EVIL 4','asdas','asdas','asdas','asdas', ))

	cell = gtk.CellRendererText()
	tvcolumn1 = gtk.TreeViewColumn('ID', cell, text=0)
	tvcolumn2 = gtk.TreeViewColumn('Juego', cell, text=0)
	tvcolumn3 = gtk.TreeViewColumn('Tamaño', cell, text=0)
	tvcolumn4 = gtk.TreeViewColumn('Tipo de juego', cell, text=0)
	tvcolumn5 = gtk.TreeViewColumn('Año', cell, text=0)

	treeview = xml.get_widget('TablaJuegos')
	treeview.append_column(tvcolumn1)
	treeview.append_column(tvcolumn2)
	treeview.append_column(tvcolumn3)
	treeview.append_column(tvcolumn4)
	treeview.append_column(tvcolumn5)
	treeview.set_model(ls)
	treeview.connect('row-activated', cb)

	ls2 = gtk.ListStore(str)
	ls3 = gtk.ListStore(str)
	ls2.append(('Accion',))
	ls2.append(('Futbol',))
	ls3.append(('2009',))
	ls3.append(('2008',))
	cell2 = gtk.CellRendererText()
	cell3 = gtk.CellRendererText()
	col2 = gtk.TreeViewColumn('Tipo de Juego', cell2, text=0)
	col3 = gtk.TreeViewColumn('Año', cell3, text=0)
	treeview2 = xml.get_widget('ListaTipoJuego')
	treeview2.append_column(col2)
	treeview3 = xml.get_widget('ListaAnio')
	treeview3.append_column(col3)
	treeview2.set_model(ls2)
	treeview3.set_model(ls3)

	
	xml.get_widget('main_window').connect('destroy', gtk.main_quit)
	gtk.main()

if ( not SALIDA_FORZADA ):	
	if( PARAMETROS[0].lower() == "listar" or PARAMETROS[0].lower() == "ls" ):
		if(hayJuegos):
			print "Listando juegos de : " + DEVICE + " " + FABRICANTE
			listarISOs(DEVICE)
			mostrarEspacioLibre(DEVICE)				
		else:
			print "No tienes instalado ningún juego en " + DEVICE + " " + FABRICANTE
	elif ( PARAMETROS[0].lower() == "instalar" or PARAMETROS[0].lower() == "install"):
		try:
			print "Inserte un juego de la Wii en su lector de DVD ..."
			raw_input("Pulse cualquier tecla para continuar ... ")
			instalarJuego(DEVICE)
		except KeyboardInterrupt:
			print
	elif ( PARAMETROS[0].lower() == "desinstalar" or PARAMETROS[0].lower() == "borrar" or PARAMETROS[0].lower() == "rm" or PARAMETROS[0].lower() == "quitar"):
		if(hayJuegos):
			if(numParametros >= 2):
				parametro = PARAMETROS[1]
				if (getExtension(parametro) == "iso"):
					IDGAME = getMagicISO(parametro)
				else:
					IDGAME = parametro
			else:
				IDGAME = get_IDJUEGO_de_Lista(DEVICE)
			print "Borrar juego con ID : " + IDGAME + " en particion " + DEVICE + " " + FABRICANTE
			if( borrarJuego(DEVICE , IDGAME) ):				
				print "Juego borrado correctmente. Refrescando lista ..."
				if( comprobarExistencia(DEVICE) and listarISOs(DEVICE)>0 and mostrarEspacioLibre(DEVICE) ):
					print "juego " + IDGAME + " borrado correctamente"
				else:
					print "Error al refrescar o no hay Juegos que listar"
			else:
				print "ERROR borrando el juego " + ID_JUEGO
		else:
			print "No hay Juegos para borrar"
			
	elif ( PARAMETROS[0].lower() == "caratula" or PARAMETROS[0].lower() == "cover"):
		if(hayJuegos):
			if(numParametros >= 2):
				IDGAME = PARAMETROS[1]
			else:
				IDGAME = get_IDJUEGO_de_Lista(DEVICE)
			if(descargarCaratula(IDGAME)):
				print "OK, descargado " + IDGAME + ".png"
			else:
				print "ERROR, descargando " + IDGAME + ".png"
		else:
			print "No hay Juegos para descargar una caratula"
	elif ( PARAMETROS[0].lower() == "caratulas" or PARAMETROS[0].lower() == "covers"):
		if(hayJuegos):
			panoramico = False
			if(numParametros >= 2): # 3 parametros
				panoramico = PARAMETROS[1].lower() == "panoramico" or PARAMETROS[1].lower() == "widescreen"
				if (panoramico):
					print "Se descargaran en formato paronámico"
			if(descargarTodasLasCaratula(DEVICE , panoramico)):
				print "OK, todas las caratulas se han descagado"
			else:
				print "ERROR, descargando alguna caratula"
				print "Vuelvelo a intentar o mira en : http://www.theotherzone.com/wii/pal.php"
		else:
			print "No hay Juegos para descargar caratulas"
	elif ( PARAMETROS[0].lower() == "renombrar" or PARAMETROS[0].lower() == "rename" or PARAMETROS[0].lower() == "r"):
		if(hayJuegos):
			if(numParametros >= 3):
				IDGAME = PARAMETROS[1]
				NUEVO_NOMBRE = PARAMETROS[2]
			else:
				IDGAME = get_IDJUEGO_de_Lista(DEVICE)
				NUEVO_NOMBRE = raw_input("Escriba el nuevo nombre : ")
			print "Renombrar juego ID : " + IDGAME + " como " + NUEVO_NOMBRE
			if ( renombrarISO(DEVICE , IDGAME , NUEVO_NOMBRE) ):
				print "Refrescando lista ..."
				if( comprobarExistencia(DEVICE) and listarISOs(DEVICE)>0 and mostrarEspacioLibre(DEVICE) ):
					print "ISO renombrada correctamente a \""+NUEVO_NOMBRE+"\""
				else:
					print "Renombrado OK aunque ocurrio un error al refrescar"
			else:
				print "ERROR al renombrar"
		else:
			print "No hay Juegos para renombrar"
	elif ( PARAMETROS[0].lower() == "check" or PARAMETROS[0].lower() == "comprobar" or PARAMETROS[0].lower() == "scandisk"):
		if(hayJuegos):
			print "Verificando todos los juegos de la particion " + DEVICE + " " + FABRICANTE
			verificarTodosLosJuegos(DEVICE)
		else:
			print "No hay Juegos para verificar"
	elif ( PARAMETROS[0].lower() == "extraer" or PARAMETROS[0].lower() == "x"):
		if(hayJuegos):
			if(numParametros >= 2):
				ID_JUEGO = PARAMETROS[1]
			else:
				ID_JUEGO = get_IDJUEGO_de_Lista(DEVICE)
			print "Extraer ISO de juego con ID : " + ID_JUEGO + " en particion " + DEVICE + " " + FABRICANTE
			if( extraerJuego(DEVICE , ID_JUEGO) ):
				print "Juego " + ID_JUEGO + " extraido OK"
			else:
				print "ERROR extrayendo la ISO de "+ID_JUEGO
		else:
			print "No hay Juegos para extraer"
	elif ( PARAMETROS[0].lower() == "ayuda" or PARAMETROS[0].lower() == "h" or PARAMETROS[0].lower() == "-h" or PARAMETROS[0].lower() == "--help" or PARAMETROS[0].lower() == "help" ): #x
		print "Listar juegos. El programa por defecto, sin parametros, hace un listado de los juegos : \n\t\t" + os.path.basename(sys.argv[0]) + "\n"
		print "Añadir ISO mediante una lista explicita de las ISOS : \n\t\t" + os.path.basename(sys.argv[0]) + " \""+RUTA+"/wii/mario.iso\" \"iso2\" \"iso3\" \"isoN\"\n"
		print "Añadir ISO con exp. reg. La expresión solo afecta al directorio actual, actualmente no es recursivo : \n\t\t" + os.path.basename(sys.argv[0]) + " *.iso\n"
		print "Buscar y Añadir ISO's recursivamente. Busca todos las imagenes isos RECURSIVAMENTE, incluso tambien busca dentro de RAR, a falta de implementar zip), tal vez necesites sudo apt-get install rar.\n\t\t" + os.path.basename(sys.argv[0]) + " buscar\n"
		print "Borrar juegos. Especificando el juego mediante un menú.: \n\t\t" + os.path.basename(sys.argv[0]) + " borrar\n"
		print "Borrar juegos. Podemos borrar con el IDGAME.: \n\t\t" + os.path.basename(sys.argv[0]) + " borrar IDJUEGO\n"
		print "Borrar juegos. Podemos borrar con el IDGAME obtenido a partir de un ISO local. El archivo ISO local NO es borrado : \n\t\t" + os.path.basename(sys.argv[0]) + " borrar \""+RUTA+"/wii/mario.iso\"\n"
		print "Renombrar juegos. Especificando el juego mediante un menú.: \n\t\t" + os.path.basename(sys.argv[0]) + " renombrar\n"
		print "Renombrar juegos, puedes cambiar el nombre de los juegos ya metidos en HD, útil para que nos enteremos cuando estemos con el USB Loader : \n\t\t" + os.path.basename(sys.argv[0]) + " renombrar IDGAME \"Mario Kart Wii\"\n"
		print "Extraer juegos a un archivo ISO. El juego es especificado mediante un menú.\n\t\t" + os.path.basename(sys.argv[0]) + " extraer\n"
		print "Extraer juegos a un archivo ISO. OJO! : El archivo ISO de salida pertenecerá a root : \n\t\t" + os.path.basename(sys.argv[0]) + " extraer IDJUEGO\n"
		print "Descargar todas las caratulas automaticamente a 160x225. Ojo puede que el servidor te banee, si te ocurre intentalo 5 minutos más tarde: \n\t\t" + os.path.basename(sys.argv[0]) + " caratulas\n"
		print "Descargar la caratulas de un juego especificado por su IDGAME, la imagen es bajada a 160x225. El comando es un singular, es \"caratula\" ya que \"caratulas\" descarga todo: \n\t\t" + os.path.basename(sys.argv[0]) + " caratula IDGAME\n"
		print "Descargar la caratulas de un juego especificado por menú, la imagen es bajada a 160x225. El comando es un singular, es \"caratula\" ya que \"caratulas\" descarga todo: \n\t\t" + os.path.basename(sys.argv[0]) + " caratula\n"
		print "Comprobar Integridad de los juegos. Muchos de nuestros juegos pueden estar corruptos sin aún saberlo debido a el bug de borrado de las primeras versiones de WBFS\n\t\t" + os.path.basename(sys.argv[0]) + " comprobar\n"
		print "Instar juegos desde el DVD, al estilo del usb loader, pero algo más lento porque dumpea a ISO y cuando termina mete la ISO.\n\t\t" + os.path.basename(sys.argv[0]) + " instalar\n"
		print
		print "Web : http://blogricardo.wordpress.com/2009/04/07/wiithon-wbfs-gui-para-wii"
	elif ( PARAMETROS[0].lower() == "buscar" or PARAMETROS[0].lower() == "meter" or PARAMETROS[0].lower() == "-r" or PARAMETROS[0].lower() == "metertodo" or PARAMETROS[0].lower() == "buscartodo"):
		print "Buscando ficheros RAR ... ",
		listaFicheros += rec_glob(".", "*.rar")
		print "OK!"
		
		print "Buscando Imagenes ISO ... ",
		listaFicheros += rec_glob(".", "*.iso")
		print "OK!"
	else:
		#Los parametros es una lista de ISOS explicita
		for parametro in PARAMETROS:
			# si tiene caracteres raros -> no es expresión regular
			# porque de otro forma, peta la expresion regular.
			if(tieneCaracteresRaros(parametro)):
				expresionExpandida = [parametro]
			else:
				expresionExpandida = glob.glob(parametro)
			for archivo in expresionExpandida:
				if	(
						os.path.isfile(archivo) and 
						(
							getExtension(archivo) == "iso" or 
							getExtension(archivo) == "rar"
						)
					):
					listaFicheros.append(archivo)
		if (len(listaFicheros) == 0):
			print "No se ha encontrado ninguna imagen ISO"

	#Ordenamos la lista
	listaFicheros.sort()
	numImagenesISO = len(listaFicheros)
	imagenesISOProcesadas=0

	if(numImagenesISO>0):
		for fichero in listaFicheros:
			imagenesISOProcesadas = imagenesISOProcesadas + 1
			print "===================== "+os.path.basename(fichero)+" ("+str(imagenesISOProcesadas)+"/"+str(numImagenesISO)+") ===================="
			print "{"
			if( comprobarExistencia(DEVICE) and comprobarExistencia(fichero) ):
				if( getExtension(fichero) == "rar" ):
					print "Añadir RAR con ISO dentro : " + os.path.basename(fichero) + " a la particion " + DEVICE + " " + FABRICANTE
					nombreRAR = fichero
					nombreISO = getNombreISOenRAR(nombreRAR)
					if (nombreISO != ""):
						if( not comprobarExistencia(nombreISO) ):
							# Paso 1 : Descomprimir
							if (descomprimirRARconISODentro(nombreRAR , nombreISO) ):
								print "Descomprimido correctamente"
								# Paso 2 : Añadir la ISO
								if ( anadirISO(DEVICE , nombreISO) ):
										mensaje = "ISO descomprimida y añadida correctamente"
										print "OK"
										print "}"
										print
										correctos.append(mensaje)
								else:
									mensaje = "ERROR añadiendo la ISO : " + nombreISO + " (comprueba que sea una ISO de WII)"
									print "ERROR"
									print "}"
									print
									erroneos.append(mensaje)
									
								# Paso 3 : Borrar la iso descomprimida
								try:
									print "Se va ha borrar la ISO descomprimida"
									os.remove(nombreISO)
									mensaje = "La ISO "+nombreISO+" temporal fue borrada"
									print "OK"
									print "}"
									print
									correctos.append(mensaje)
								except:
									mensaje = "ERROR al borrar la ISO : " + nombreISO
									print "ERROR"
									print "}"
									print
									erroneos.append(mensaje)
							else:
								mensaje = "ERROR al descomrpimir el RAR : " + nombreRAR
								print "ERROR"
								print "}"
								print
								erroneos.append(mensaje)
						else:
							mensaje = "ERROR no se puede descomrpimir por que reemplazaría el ISO : " + nombreISO
							print "ERROR"
							print "}"
							print
							erroneos.append(mensaje)
					else:
						mensaje = "ERROR el RAR " + nombreRAR + " no tenía ninguna ISO"
						print "ERROR"
						print "}"
						print
						erroneos.append(mensaje)
				elif( getExtension(fichero) == "iso" ):					
					print "Añadir ISO : " + os.path.basename(fichero) + " a la particion " + DEVICE + " " + FABRICANTE
					if ( anadirISO(DEVICE , fichero) ):
						mensaje = "ISO añadida correctamente"
						print "OK"
						print "}"
						print
						correctos.append(mensaje)
					else:
						mensaje = "ERROR añadiendo la ISO : " + fichero + " (comprueba que sea una ISO de WII)"
						print "ERROR"
						print "}"
						print
						erroneos.append(mensaje)
			else:
				mensaje = "ERROR la ISO o la partición no existe"
				print "ERROR"
				print "}"
				print
				erroneos.append(mensaje)

		print "================= INFORME DE RESULTADOS ========================="
		print "{"

		if(len(correctos) == imagenesISOProcesadas):
			print "\t{"
			print "\t================= Todo metido en el HD correctamente ==================="
			print "\t}"
		else:
			if(len(correctos) > 0):
				print "\t================ Juegos correctos ("+str(len(correctos))+"/"+str(imagenesISOProcesadas)+") =============="
				print "\t{"
				for mensaje in correctos:
					print "\t"+mensaje
				print "\t}"

		if(len(erroneos) > 0):
			print "\t=================== Juegos erroneos ("+str(len(erroneos))+"/"+str(imagenesISOProcesadas)+") ================="
			print "\t{"
			for mensaje in erroneos:
				print "\t"+mensaje
			print "\t}"

		print "}"

if (not GUI and PAUSA):
	raw_input("Pulse cualquier tecla para continuar ...\n")
