#!/bin/bash

for i in $(cat /proc/partitions | grep -v name | sed '/^$/d' | awk '{print "/dev/" $4}' | egrep '(s|h)d([a-z])([0-9])');
do
	RES=`udevinfo -a -p $(udevinfo -q path -n $i) | grep 'SUBSYSTEMS=="usb"' | wc -l 2> /dev/null`
	if [ $RES -gt 0 ]; then
		MAGICO=`sudo head --bytes=4 $i`
		if [ $MAGICO == "WBFS" ]; then
			echo $i;
		fi
	fi
done

#udevinfo -a -p $(udevinfo -q path -n /dev/sdb1) | egrep 'ATTRS{product}|ATTRS{manufacturer}' | awk -F== '{print $2}' | xargs
