#!/bin/sh

ln -s /usr/local/lib/libwbfs.so /usr/lib/
if [ $(uname -m) =  "x86_64" ] 
then
	ln -s /usr/local/lib/libwbfs.so /lib32/
fi
ln -s /usr/local/share/wiithon/wiithon.py /usr/local/bin/wiithon
ln -s /usr/local/share/wiithon/wiithon_wrapper /usr/local/bin/wiithon_wrapper
