
//---------------------------------"
// This file is generated by make."
// Any changes will be lost!"
//---------------------------------"

#define WWT_SHORT	"wwt"
#define WWT_LONG	"Wiimms WBFS Tool"
#define WIT_SHORT	"wit"
#define WIT_LONG	"Wiimms ISO Tool"
#define AUTHOR		"Dirk Clemens"

#define VERSION		"0.19b"
#define REVISION	"495M"
#define REVISION_NUM	495
#define REVISION_NEXT	496

#define BINTIME		1259442777
#define DATE		"2009-11-28"
#define TIME		"22:12:57"
#define DATETIME	"2009-11-28 22:12:57"

#define URI_REPOS	"http://opensvn.wiimm.de/wii/trunk/wiimms-wbfs-tool/"
#define URI_VIEWVC	"http://opensvn.wiimm.de/viewvc/wii/trunk/wiimms-wbfs-tool/"
#define URI_GBATEMP	"http://gbatemp.net/index.php?showtopic=182236#entry2286365"
#define URI_DOWNLOAD	"@@URI-DOWNLOAD@@"

