
//---------------------------------"
// This file is generated by make."
// Any changes will be lost!"
//---------------------------------"

#define WWT_SHORT	"wwt"
#define WWT_LONG	"Wiimms WBFS Tool"
#define WIT_SHORT	"wit"
#define WIT_LONG	"Wiimms ISO Tool"
#define AUTHOR		"Dirk Clemens"

#define VERSION		"0.21a"
#define REVISION	"522M"
#define REVISION_NUM	522
#define REVISION_NEXT	523

#define BINTIME		1260516066
#define DATE		"2009-12-11"
#define TIME		"08:21:06"
#define DATETIME	"2009-12-11 08:21:06"

#define URI_REPOS	"http://opensvn.wiimm.de/wii/trunk/wiimms-wbfs-tool/"
#define URI_VIEWVC	"http://opensvn.wiimm.de/viewvc/wii/trunk/wiimms-wbfs-tool/"
#define URI_HOME	"http://wiimm.de/wwt/"
#define URI_DOWNLOAD	"@@URI-DOWNLOAD@@"

