
//---------------------------------"
// This file is generated by make."
// Any changes will be lost!"
//---------------------------------"

#define WWT_SHORT	"wwt"
#define WWT_LONG	"Wiimms WBFS Tool"
#define WIT_SHORT	"wit"
#define WIT_LONG	"Wiimms ISO Tool"
#define AUTHOR		"Dirk Clemens"

#define VERSION		"0.32a"
#define REVISION	"633M"
#define REVISION_NUM	633
#define REVISION_NEXT	634

#define BINTIME		1266535648
#define DATE		"2010-02-19"
#define TIME		"00:27:28"
#define DATETIME	"2010-02-19 00:27:28"

#define URI_REPOS	"http://opensvn.wiimm.de/wii/trunk/wiimms-wbfs-tool/"
#define URI_VIEWVC	"http://opensvn.wiimm.de/viewvc/wii/trunk/wiimms-wbfs-tool/"
#define URI_HOME	"http://wiimm.de/wwt/"
#define URI_DOWNLOAD	"@@URI-DOWNLOAD@@"

